version: "3.9"

services:
  web:
    image: joshikunal/netflix:latest
    build: .
    ports:
      - "3000:3000"
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - webnet

networks:
  webnet:
    driver: overlay



