version: '3.7'

services:
  netflix:
    image: joshikunal/netflix:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
    networks:
      - netflix-net

networks:
  netflix-net:
    driver: overlay



