version: '3'
services:
  web:
    image: nginx:alpine
    container_name: netflix_login_page
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
