version: '3.8'

services:
  web:
    image: joshikunal/netflix:latest
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet:
    driver: overlay

